import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/NavBar';
import { WalletProvider } from '@/context/WalletContext'; // Import WalletProvider

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
      <Navbar />
        <WalletProvider> {/* Wrap with WalletProvider */}
          <div className="flex flex-col min-h-screen"> {/* Flex container to ensure full height */}
            <main className="flex-grow"> {/* Flex grow to take remaining space */}
              {children}
            </main>
          </div>
        </WalletProvider>
      </body>
    </html>
  );
}
